version: '3.8'

services:

  sql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

#  auth-api:
    #image: 
   # build: 
   #   context: ..
   #   dockerfile: Auth-Services/Dockerfile
   # depends_on:
    #  - sql-db

  account-api:
    #image: 
    build: 
      context: ../Account-Service/src
      dockerfile: Point.Services.Account.Api/Dockerfile
    depends_on:
      - sql-db
    #  - auth-api

  shop-api:
    #image: 
    build: 
      context: ../Shop-Service/src
      dockerfile: Point.Services.Shops.Api/Dockerfile
    depends_on:
      - sql-db
    #  - auth-api

  card-api:
    #image: 
    build: 
      context: ../Card-Service/src
      dockerfile: Point.Services.Card.Api/Dockerfile 
    depends_on:
      - sql-db
    #  - auth-api

  gateway:
    #image: 
    build: 
      context: ../Ocelot-ApiGateways
      dockerfile: Point.ApiGateways.Ocelot/Dockerfile
    depends_on:
      - sql-db
    #  - auth-api
      - account-api
      - shop-api
      - card-api
  #vue-admin:
  