version: '3.8'

services:

  sql-db:
    environment:
      MYSQL_ROOT_PASSWORD: dev-password
    ports:
      - "3306:3306"
    volumes:
      - point-sqldata:/var/lib/mysql

  auth-api:
    environment:
    ports:

  account-api:
    environment:
    ports:

  shop-api:
    environment:
    ports:

  card-api:
    environment:
    ports:

  notification-api:
    environment:
    ports:

  gateway:
    environment:
    ports:

volumes:
  point-sqldata:
    xternal: false

