version: '3.8'

services:

  sql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  identity-api:
    #image: 
    build: 
      context: ../Auth-Service/src
      dockerfile: Point.Services.Identity.Api/Dockerfile
    depends_on:
      - sql-db

  point-api:
    #image: 
    build: 
      context: ../Point.API/src
      dockerfile: Point.API/Dockerfile
    depends_on:
      - sql-db
      - identity-api

  #vue-admin:
  