version: '3.8'

services:

  sql-db:
    environment:
    ports:
    volumes:

  auth-api:
    environment:
    ports:

  account-api:
    environment:
    ports:

  shop-api:
    environment:
    ports:

  card-api:
    environment:
    ports:

  notification-api:
    environment:
    ports:

  gateway:
    environment:
    ports:

volumes:


