version: '3.8'

services:

  sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    restart: always

  identity-api:
    #image: 
    build: 
      context: ../Auth-Service/src
      dockerfile: Point.Services.Identity.Api/Dockerfile
    container_name: identity
    depends_on:
      - sql-db

  point-api:
    #image: 
    build: 
      context: ../Point.API/src
      dockerfile: Point.API/Dockerfile
    container_name: main-api
    depends_on:
      - sql-db
      - identity-api

  #vue-admin:
  